# Generated by Django 3.1.7 on 2021-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combaterincendio', '0008_auto_20210331_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Logo')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Ordem')),
                ('website_link', models.URLField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('order',),
            },
        ),
    ]
