# Generated by Django 3.1.7 on 2021-04-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combaterincendio', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto')),
                ('message', models.TextField(blank=True, max_length=100, null=True, verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Site - Contato',
                'verbose_name_plural': 'Site - Contatos',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
