# Generated by Django 3.1.7 on 2022-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combaterincendio', '0011_auto_20210402_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('diferencial', models.CharField(max_length=100, verbose_name='Diferencial')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Grafico'), ('lni-users', 'Usuarios'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Computador'), ('lni-leaf', 'Folha'), ('lni-layers', 'Pilha')], max_length=20, verbose_name='Icone')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Diferencial ',
                'verbose_name_plural': 'Diferencial ',
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='DiferencialDireito',
        ),
        migrations.DeleteModel(
            name='DiferencialEsquerdo',
        ),
    ]
